import Solution
set_option pp.universes true
set_option pp.explicit true
#assert_trust kernel NLA.SP05.kronecker_columnVec
#print axioms NLA.SP05.kronecker_columnVec
#assert_trust kernel NLA.SP05.commutation_mulVec
#print axioms NLA.SP05.commutation_mulVec
#assert_trust kernel NLA.SP05.commutation_columnVec
#print axioms NLA.SP05.commutation_columnVec
#assert_trust kernel NLA.SP05.columnVec_dot_self
#print axioms NLA.SP05.columnVec_dot_self
#assert_trust kernel NLA.SP05.columnVec_ne_zero
#print axioms NLA.SP05.columnVec_ne_zero
#assert_trust kernel NLA.SP05.dot_self_pos
#print axioms NLA.SP05.dot_self_pos
#assert_trust kernel NLA.SP05.skew_transpose
#print axioms NLA.SP05.skew_transpose
#assert_trust kernel NLA.SP05.skew_frobenius
#print axioms NLA.SP05.skew_frobenius
#assert_trust kernel NLA.SP05.skew_frobenius_pos
#print axioms NLA.SP05.skew_frobenius_pos
#assert_trust kernel NLA.SP05.skew_ne_zero
#print axioms NLA.SP05.skew_ne_zero
#assert_trust kernel NLA.SP05.skew_norm_positive_certificate
#print axioms NLA.SP05.skew_norm_positive_certificate
#assert_trust kernel NLA.SP05.complexify_apply
#print axioms NLA.SP05.complexify_apply
#assert_trust kernel NLA.SP05.complexifyHom_apply
#print axioms NLA.SP05.complexifyHom_apply
#assert_trust kernel NLA.SP05.complexify_injective
#print axioms NLA.SP05.complexify_injective
#assert_trust kernel NLA.SP05.complexify_zero
#print axioms NLA.SP05.complexify_zero
#assert_trust kernel NLA.SP05.complexify_eq_zero
#print axioms NLA.SP05.complexify_eq_zero
#assert_trust kernel NLA.SP05.complexify_add
#print axioms NLA.SP05.complexify_add
#assert_trust kernel NLA.SP05.complexify_sub
#print axioms NLA.SP05.complexify_sub
#assert_trust kernel NLA.SP05.complexify_smul
#print axioms NLA.SP05.complexify_smul
#assert_trust kernel NLA.SP05.complexify_star
#print axioms NLA.SP05.complexify_star
#assert_trust kernel NLA.SP05.complexify_conjTranspose
#print axioms NLA.SP05.complexify_conjTranspose
#assert_trust kernel NLA.SP05.complexify_transpose
#print axioms NLA.SP05.complexify_transpose
#assert_trust kernel NLA.SP05.complexify_one
#print axioms NLA.SP05.complexify_one
#assert_trust kernel NLA.SP05.complexify_mul
#print axioms NLA.SP05.complexify_mul
#assert_trust kernel NLA.SP05.complexify_posSemidef
#print axioms NLA.SP05.complexify_posSemidef
#assert_trust kernel NLA.SP05.complexify_posDef
#print axioms NLA.SP05.complexify_posDef
#assert_trust kernel NLA.SP05.complexify_inv
#print axioms NLA.SP05.complexify_inv
#assert_trust kernel NLA.SP05.complexify_sqrt
#print axioms NLA.SP05.complexify_sqrt
#assert_trust kernel NLA.SP05.complexify_abs
#print axioms NLA.SP05.complexify_abs
#assert_trust kernel NLA.SP05.complexify_abs_I_smul
#print axioms NLA.SP05.complexify_abs_I_smul
#assert_trust kernel NLA.SP05.complexify_kronecker
#print axioms NLA.SP05.complexify_kronecker
#assert_trust kernel NLA.SP05.complex_jordan_columnVec
#print axioms NLA.SP05.complex_jordan_columnVec
#assert_trust kernel NLA.SP05.actual_jordan_inverse_equation
#print axioms NLA.SP05.actual_jordan_inverse_equation
#assert_trust kernel NLA.SP05.actual_jordan_inverse_cone
#print axioms NLA.SP05.actual_jordan_inverse_cone
#assert_trust kernel NLA.SP05.jordan_posDef
#print axioms NLA.SP05.jordan_posDef
#assert_trust kernel NLA.SP05.jordan_commutation
#print axioms NLA.SP05.jordan_commutation
#assert_trust kernel NLA.SP05.jordan_inverse_commutation
#print axioms NLA.SP05.jordan_inverse_commutation
#assert_trust kernel NLA.SP05.real_eigenmatrix_sign
#print axioms NLA.SP05.real_eigenmatrix_sign
#assert_trust kernel NLA.SP05.jordan_inverse_top_sign
#print axioms NLA.SP05.jordan_inverse_top_sign
#assert_trust kernel NLA.SP05.inverse_eigen_to_eigen
#print axioms NLA.SP05.inverse_eigen_to_eigen
#assert_trust kernel NLA.SP05.rayleigh_lower_of_slack
#print axioms NLA.SP05.rayleigh_lower_of_slack
#assert_trust kernel NLA.SP05.global_positive_minimizer
#print axioms NLA.SP05.global_positive_minimizer
#assert_trust kernel NLA.SP05.vec_realMatrixAction
#print axioms NLA.SP05.vec_realMatrixAction
#assert_trust kernel NLA.SP05.vec_complexMatrixAction
#print axioms NLA.SP05.vec_complexMatrixAction
#assert_trust kernel NLA.SP05.complexMatrixAction_real
#print axioms NLA.SP05.complexMatrixAction_real
#assert_trust kernel NLA.SP05.complexPairing_trace
#print axioms NLA.SP05.complexPairing_trace
#assert_trust kernel NLA.SP05.complexPairing_real
#print axioms NLA.SP05.complexPairing_real
#assert_trust kernel NLA.SP05.complexPairing_I
#print axioms NLA.SP05.complexPairing_I
#assert_trust kernel NLA.SP05.trace_product_posSemidef_nonneg
#print axioms NLA.SP05.trace_product_posSemidef_nonneg
#assert_trust kernel NLA.SP05.complexPairing_posSemidef_nonneg
#print axioms NLA.SP05.complexPairing_posSemidef_nonneg
#assert_trust kernel NLA.SP05.hermitian_modulus_pairing_le
#print axioms NLA.SP05.hermitian_modulus_pairing_le
#assert_trust kernel NLA.SP05.real_abs_vec_norm_sq
#print axioms NLA.SP05.real_abs_vec_norm_sq
#assert_trust kernel NLA.SP05.modulus_quadratic_improves
#print axioms NLA.SP05.modulus_quadratic_improves
#assert_trust kernel NLA.SP05.numerical_bound
#print axioms NLA.SP05.numerical_bound
#assert_trust kernel NLA.SP05.column_vectorization
#print axioms NLA.SP05.column_vectorization
#assert_trust kernel NLA.SP05.skew_witness
#print axioms NLA.SP05.skew_witness
#assert_trust kernel NLA.SP05.positive_minimizer
#print axioms NLA.SP05.positive_minimizer
#assert_trust kernel NLA.SP05.sector_minima
#print axioms NLA.SP05.sector_minima
#assert_trust kernel NLA.SP05.canonical_result
#print axioms NLA.SP05.canonical_result
#assert_trust kernel NLA.SP05.dot_self_smul
#print axioms NLA.SP05.dot_self_smul
#assert_trust kernel NLA.SP05.rayleigh_smul
#print axioms NLA.SP05.rayleigh_smul
#assert_trust kernel NLA.SP05.normalize_sector
#print axioms NLA.SP05.normalize_sector
#assert_trust kernel NLA.SP05.unitSector_isCompact
#print axioms NLA.SP05.unitSector_isCompact
#assert_trust kernel NLA.SP05.unitSector_ne_zero
#print axioms NLA.SP05.unitSector_ne_zero
#assert_trust kernel NLA.SP05.sector_minimum_exists
#print axioms NLA.SP05.sector_minimum_exists
#assert_trust kernel NLA.SP05.symmetric_sector_nonempty
#print axioms NLA.SP05.symmetric_sector_nonempty
#assert_trust kernel NLA.SP05.skew_sector_nonempty
#print axioms NLA.SP05.skew_sector_nonempty
#assert_trust kernel NLA.SP05.both_sector_minima
#print axioms NLA.SP05.both_sector_minima
#assert_trust kernel NLA.SP05.commutation_dot
#print axioms NLA.SP05.commutation_dot
#assert_trust kernel NLA.SP05.commutation_kronecker
#print axioms NLA.SP05.commutation_kronecker
#assert_trust kernel NLA.SP05.sector_rayleigh_twice
#print axioms NLA.SP05.sector_rayleigh_twice
#assert_trust kernel NLA.SP05.rayleigh_of_eigenvector
#print axioms NLA.SP05.rayleigh_of_eigenvector
#assert_trust kernel NLA.SP05.sector_comparison_of_psd_minimizer
#print axioms NLA.SP05.sector_comparison_of_psd_minimizer
#assert_trust kernel NLA.SP05.real_spectral_max
#print axioms NLA.SP05.real_spectral_max
#assert_trust kernel NLA.SP05.psd_slack_eigenvector
#print axioms NLA.SP05.psd_slack_eigenvector
#assert_trust kernel NLA.SP05.inverse_slack_lower
#print axioms NLA.SP05.inverse_slack_lower
#assert_trust kernel NLA.SP05.sylvester_posSemidef
#print axioms NLA.SP05.sylvester_posSemidef
#assert_trust kernel NLA.SP05.complex_jordan_injective
#print axioms NLA.SP05.complex_jordan_injective
#assert_trust kernel NLA.SP05.complex_jordan_preimage_hermitian
#print axioms NLA.SP05.complex_jordan_preimage_hermitian
#assert_trust kernel NLA.SP05.complex_jordan_preimage_posSemidef
#print axioms NLA.SP05.complex_jordan_preimage_posSemidef
#assert_trust kernel NLA.SP05.complex_jordan_solution_posSemidef
#print axioms NLA.SP05.complex_jordan_solution_posSemidef
#check @NLA.SP05.numerical_bound
#check @NLA.SP05.column_vectorization
#check @NLA.SP05.skew_witness
#check @NLA.SP05.positive_minimizer
#check @NLA.SP05.sector_minima
#check @NLA.SP05.canonical_result
