import NLA.SP04.Diagonal
import NLA.SP04.Generic
import NLA.SP04.Orthogonal

#assert_trust kernel NLA.SP04.scalar_numerical_bounds
#print axioms NLA.SP04.scalar_numerical_bounds
#assert_trust kernel NLA.SP04.scalar_admissible_bounds
#print axioms NLA.SP04.scalar_admissible_bounds
#assert_trust kernel NLA.SP04.scalar_admissible_pos
#print axioms NLA.SP04.scalar_admissible_pos
#assert_trust kernel NLA.SP04.negative_roots
#print axioms NLA.SP04.negative_roots
#assert_trust kernel NLA.SP04.negativeMagnitude_pos
#print axioms NLA.SP04.negativeMagnitude_pos
#assert_trust kernel NLA.SP04.negative_quadratic_roots
#print axioms NLA.SP04.negative_quadratic_roots
#assert_trust kernel NLA.SP04.positiveRoot_continuous
#print axioms NLA.SP04.positiveRoot_continuous
#assert_trust kernel NLA.SP04.negativeMagnitude_continuous
#print axioms NLA.SP04.negativeMagnitude_continuous
#assert_trust kernel NLA.SP04.negative_roots_parameter_strict
#print axioms NLA.SP04.negative_roots_parameter_strict
#assert_trust kernel NLA.SP04.negative_roots_order
#print axioms NLA.SP04.negative_roots_order
#assert_trust kernel NLA.SP04.selectedProduct_continuous
#print axioms NLA.SP04.selectedProduct_continuous
#assert_trust kernel NLA.SP04.selectedProduct_strict
#print axioms NLA.SP04.selectedProduct_strict
#assert_trust kernel NLA.SP04.selectedProduct_zero
#print axioms NLA.SP04.selectedProduct_zero
#assert_trust kernel NLA.SP04.selectedProduct_endpoint
#print axioms NLA.SP04.selectedProduct_endpoint
#assert_trust kernel NLA.SP04.selected_parameter_exists
#print axioms NLA.SP04.selected_parameter_exists
#assert_trust kernel NLA.SP04.positive_discriminant
#print axioms NLA.SP04.positive_discriminant
#assert_trust kernel NLA.SP04.nonnegative_roots
#print axioms NLA.SP04.nonnegative_roots
#assert_trust kernel NLA.SP04.nonnegative_quadratic_roots
#print axioms NLA.SP04.nonnegative_quadratic_roots
#assert_trust kernel NLA.SP04.nonnegative_roots_order
#print axioms NLA.SP04.nonnegative_roots_order
#assert_trust kernel NLA.SP04.largeRoot_difference
#print axioms NLA.SP04.largeRoot_difference
#assert_trust kernel NLA.SP04.nonnegative_product_bound
#print axioms NLA.SP04.nonnegative_product_bound
#assert_trust kernel NLA.SP04.nonnegative_scalar_impossible
#print axioms NLA.SP04.nonnegative_scalar_impossible
#assert_trust kernel NLA.SP04.negative_scalar_comparison
#print axioms NLA.SP04.negative_scalar_comparison
#assert_trust kernel NLA.SP04.scalar_least_unique
#print axioms NLA.SP04.scalar_least_unique
#assert_trust kernel NLA.SP04.selected_scalar_stationary
#print axioms NLA.SP04.selected_scalar_stationary
#assert_trust kernel NLA.SP04.improved_scalar_feasible
#print axioms NLA.SP04.improved_scalar_feasible
#assert_trust kernel NLA.SP04.scalar_distance_improves
#print axioms NLA.SP04.scalar_distance_improves
#assert_trust kernel NLA.SP04.diagonal_difference_frobeniusSq
#print axioms NLA.SP04.diagonal_difference_frobeniusSq
#assert_trust kernel NLA.SP04.selected_unique_least
#print axioms NLA.SP04.selected_unique_least
#assert_trust kernel NLA.SP04.diagonal_counterexample_full
#print axioms NLA.SP04.diagonal_counterexample_full
#assert_trust kernel NLA.SP04.feasible_det_ne_zero
#print axioms NLA.SP04.feasible_det_ne_zero
#assert_trust kernel NLA.SP04.stationary_cross
#print axioms NLA.SP04.stationary_cross
#assert_trust kernel NLA.SP04.stationary_other_cross
#print axioms NLA.SP04.stationary_other_cross
#assert_trust kernel NLA.SP04.stationary_gram_commutes
#print axioms NLA.SP04.stationary_gram_commutes
#assert_trust kernel NLA.SP04.admissible_pos
#print axioms NLA.SP04.admissible_pos
#assert_trust kernel NLA.SP04.admissible_injective
#print axioms NLA.SP04.admissible_injective
#assert_trust kernel NLA.SP04.admissible_sq_injective
#print axioms NLA.SP04.admissible_sq_injective
#assert_trust kernel NLA.SP04.stationary_diagonal_gram
#print axioms NLA.SP04.stationary_diagonal_gram
#assert_trust kernel NLA.SP04.stationary_diagonal_matrix
#print axioms NLA.SP04.stationary_diagonal_matrix
#assert_trust kernel NLA.SP04.all_diagonal_stationary_iff
#print axioms NLA.SP04.all_diagonal_stationary_iff
#assert_trust kernel NLA.SP04.polynomial_avoids_open
#print axioms NLA.SP04.polynomial_avoids_open
#assert_trust kernel NLA.SP04.orthogonal_transpose
#print axioms NLA.SP04.orthogonal_transpose
#assert_trust kernel NLA.SP04.orthogonal_abs_det
#print axioms NLA.SP04.orthogonal_abs_det
#assert_trust kernel NLA.SP04.orthogonal_inverse_transport
#print axioms NLA.SP04.orthogonal_inverse_transport
#assert_trust kernel NLA.SP04.orthogonal_cancel_left
#print axioms NLA.SP04.orthogonal_cancel_left
#assert_trust kernel NLA.SP04.feasible_orthogonal_iff
#print axioms NLA.SP04.feasible_orthogonal_iff
#assert_trust kernel NLA.SP04.frobeniusSq_eq_trace
#print axioms NLA.SP04.frobeniusSq_eq_trace
#assert_trust kernel NLA.SP04.frobeniusSq_orthogonal
#print axioms NLA.SP04.frobeniusSq_orthogonal
#assert_trust kernel NLA.SP04.frobeniusNorm_orthogonal
#print axioms NLA.SP04.frobeniusNorm_orthogonal
#assert_trust kernel NLA.SP04.orthogonal_stationary_expression
#print axioms NLA.SP04.orthogonal_stationary_expression
#assert_trust kernel NLA.SP04.stationary_orthogonal_forward
#print axioms NLA.SP04.stationary_orthogonal_forward
#assert_trust kernel NLA.SP04.stationary_orthogonal_iff
#print axioms NLA.SP04.stationary_orthogonal_iff
#assert_trust kernel NLA.SP04.full_orthogonal_transport
#print axioms NLA.SP04.full_orthogonal_transport
