import Mathlib

#check Matrix.vec
#check Matrix.vec_transpose
#check Matrix.vec_bijective
#check Matrix.vec_eq_zero_iff
#check Matrix.kronecker_mulVec_vec
#check Matrix.vec_dotProduct_vec
#check Matrix.star_vec_dotProduct_vec
#check Matrix.PosDef.kronecker
#check Matrix.PosDef.inv
#check Matrix.PosDef.isUnit
#check Matrix.PosDef.conjTranspose_mul_mul_same
#check Matrix.PosSemidef.conjTranspose_mul_mul_same
#check Matrix.PosSemidef.trace_nonneg
#check Matrix.PosSemidef.re_dotProduct_nonneg
#check Matrix.PosDef.re_dotProduct_pos
#check Matrix.IsHermitian.posSemidef_iff_eigenvalues_nonneg
#check Matrix.IsHermitian.mulVec_eigenvectorBasis
#check Matrix.IsHermitian.spectral_theorem
#check Matrix.IsHermitian.cfc_eq
#check CFC.sqrt_nonneg
#check CFC.sqrt_mul_sqrt_self
#check CFC.sqrt_unique
#check CFC.isUnit_sqrt_iff
#check CFC.posPart_nonneg
#check CFC.negPart_nonneg
#check CFC.posPart_sub_negPart
#check CFC.posPart_mul_negPart
#check CFC.posPart_add_negPart
#check CFC.abs_smul
#check CFC.abs_sq
#check CFC.abs_eq_zero_iff
#check Matrix.trace_mul_cycle
#check IsSelfAdjoint.hasEigenvector_of_isMaxOn
#check LinearMap.IsSymmetric.hasEigenvalue_iSup_of_finiteDimensional
#check LinearMap.IsSymmetric.hasEigenvalue_iInf_of_finiteDimensional
